# Site settings
title:          Rankloud Coupons
description:    "Rankloud Coupons and Promo Codes for 2025"
url:            "https://rankloud.github.io/ibcs"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Rankloud
  url:          https://rankloud.com
  email:        rankloud@gmail.com

## Custom
collections:
  _wp:
    output: true
    permalink: /wp/:name/

# Build settings
remote_theme: chesterhow/tale
markdown:       kramdown
include:
  - _pages
  - _wp
  - _posts

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /pretty
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale